services:
  mf_drawer:
    build:
      context: ./front/mf_drawer
    ports:
      - "8000:3000"
    volumes:
      - ./front/mf_drawer/src:/app/src
    depends_on:
      - drawer_services
      - videos_services

  mf_videos:
    build:
      context: ./front/mf_videos
    ports:
      - "8001:3000"
    volumes:
      - ./front/mf_videos/src:/app/src
    depends_on:
      - drawer_services
      - videos_services

  drawer_services:
    build:
      context: ./bff/drawer_services
    ports:
      - "3000:3000"

  videos_services:
    build:
      context: ./bff/videos_services
    ports:
      - "3001:3000"
    env_file:
      - "./bff/.env"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mf_drawer
      - mf_videos
